
# Se quiser rodar sua maquina Vagrant na AWS, configure a informacao abaixo
# AWS Access Key e arquivo .pem
aws_access_key_id: ""
aws_secret_access_key: ""
aws_keypair_name: "/home/user/file.pem"

# Lista dos AWS Security groups
aws_security_groups: ["default"]

# AWS AMI Base (a AMI abaixo eh pulica, mas voce pode criar uma propria se preferir)
aws_ami: "ami-bd6d40d4"

# Tipo da instancia e regiao AWS
instance_type: "m1.small"
aws_region: "us-east-1"

# Informacoes para logar na maquina
# Usuario (use "ubuntu" se voce manter a aws_ami exemplo (ami-bd6d40d4) 
default_username: "ubuntu"
ssh_private_key_path: "/home/user/chaveSSHpublica.pem"
